#!/usr/bin/with-contenv bash
#shellcheck shell=bash

sleep 1

if [[ -z "$SOAPY" ]]; then
    echo "SOAPY env var must be set" 2>&1 | stdbuf -o0 awk '{print "[soapy] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    sleep 86400
fi

retry_seconds=1
while ! SoapySDRUtil --find=$SOAPY; do
    echo "SoapySDR device not found, retrying in $retry_seconds seconds!"
    sleep $retry_seconds
    retry_seconds=$((retry_seconds + 1))
    if (( retry_seconds > 60 )); then
        retry_seconds=60
    fi
done

python -u /scripts/soapy2tcp.py 2>&1 | stdbuf -o0 awk '{print "[soapy] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
