#!/usr/bin/with-contenv bash
#shellcheck shell=bash

sleep 1

while ! SoapySDRUtil --find; do
    echo "No SoapySDR devices found!"
    s6-svc -r /run/s6/services/sdrplay
    sleep 10
done

if [[ -z "$SOAPY" ]]; then
    echo "SOAPY env var must be set" 2>&1 | stdbuf -o0 awk '{print "[soapy] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    sleep 86400
else
    python -u /scripts/soapy2tcp.py 2>&1 | stdbuf -o0 awk '{print "[soapy] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi
